[package]
org = "wso2"
name = "greeter"
version = "0.1.0"
distribution = "2201.1.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "com.microsoft.sqlserver"
artifactId = "mssql-jdbc"
version = "9.2.0.jre11"